name: st_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _r-mutex=1.0.1=anacondar_1
  - bwidget=1.10.1=hce30654_1
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - cctools_impl_osx-arm64=1030.6.3=llvm21_1_haddd2d4_1
  - cctools_osx-arm64=1030.6.3=llvm21_1_h6d92914_1
  - clang=21.1.7=default_hf9bcbb7_1
  - clang-21=21.1.7=default_h489deba_1
  - clang_impl_osx-arm64=21.1.7=hf07ed8f_28
  - clang_osx-arm64=21.1.7=h07b0088_28
  - clangxx=21.1.7=default_h36137df_1
  - clangxx_impl_osx-arm64=21.1.7=h13236d4_28
  - clangxx_osx-arm64=21.1.7=h07b0088_28
  - compiler-rt=21.1.7=hce30654_0
  - compiler-rt21=21.1.7=h855ad52_0
  - compiler-rt21_osx-arm64=21.1.7=h2514db7_0
  - curl=8.17.0=hdece5d2_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - gfortran_impl_osx-arm64=14.3.0=h6d03799_1
  - gfortran_osx-arm64=14.3.0=h3c33bd0_0
  - gmp=6.3.0=h7bae524_2
  - graphite2=1.3.14=hec049ff_2
  - gsl=2.7=h6e638da_0
  - harfbuzz=12.2.0=haf38c7b_0
  - icu=75.1=hfee45f7_0
  - isl=0.26=imath32_h347afa1_101
  - krb5=1.21.3=h237132a_0
  - ld64=956.6=llvm21_1_h5d6df6c_1
  - ld64_osx-arm64=956.6=llvm21_1_hde6573c_1
  - lerc=4.0.0=hd64df32_1
  - libasprintf=0.25.1=h493aca8_0
  - libblas=3.11.0=5_h51639a9_openblas
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libclang-cpp21.1=21.1.7=default_h73dfc95_1
  - libcurl=8.17.0=hdece5d2_1
  - libcxx=21.1.8=hf598326_0
  - libcxx-devel=21.1.8=h6dc3340_0
  - libcxx-headers=21.1.8=h707e725_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgettextpo=0.25.1=h493aca8_0
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran-devel_osx-arm64=14.3.0=hc965647_1
  - libgfortran5=15.2.0=hdae7583_16
  - libglib=2.86.3=hfe11c1f_0
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - libllvm21=21.1.7=h8e0c9ce_0
  - liblzma=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libpng=1.6.53=hfab5511_0
  - libsigtool=0.1.3=h98dc951_0
  - libsodium=1.0.20=h99b78c6_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.1=h4030677_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.8=h4a912ad_0
  - llvm-tools=21.1.7=h855ad52_0
  - llvm-tools-21=21.1.7=h91fd4e7_0
  - make=4.4.1=hc9fafa5_2
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - ncurses=6.5=h5e97a16_3
  - openssl=3.6.0=h5503f6c_0
  - pango=1.56.4=h875632e_0
  - pcre2=10.47=h30297fc_0
  - pixman=0.46.4=h81086ad_1
  - r-base=4.5.2=hb2e0d2d_3
  - r-base64enc=0.1_3=r45h6168396_1008
  - r-cli=3.6.5=r45hc1cd577_1
  - r-crayon=1.5.3=r45hc72bb7e_2
  - r-digest=0.6.39=r45hc1cd577_0
  - r-ellipsis=0.3.2=r45h6168396_4
  - r-evaluate=1.0.5=r45hc72bb7e_1
  - r-fansi=1.0.7=r45h6168396_0
  - r-fastmap=1.2.0=r45hc1cd577_2
  - r-glue=1.8.0=r45h6168396_1
  - r-htmltools=0.5.9=r45hc1cd577_0
  - r-irdisplay=1.1=r45hd8ed1ab_4
  - r-irkernel=1.3.2=r45h785f33e_3
  - r-jsonlite=2.0.0=r45h6168396_1
  - r-lifecycle=1.0.4=r45hc72bb7e_2
  - r-pbdzmq=0.3_14=r45h350048c_1
  - r-pillar=1.11.1=r45hc72bb7e_0
  - r-repr=1.1.7=r45h785f33e_2
  - r-rlang=1.1.6=r45hc1cd577_1
  - r-utf8=1.2.6=r45h6168396_1
  - r-uuid=1.2_1=r45h6168396_1
  - r-vctrs=0.6.5=r45hc1cd577_2
  - readline=8.3=h46df422_0
  - sdkroot_env_osx-arm64=14.5=hfa17104_3
  - sigtool=0.1.3=h98dc951_0
  - sigtool-codesign=0.1.3=h98dc951_0
  - tapi=1600.0.11.8=h997e182_0
  - tk=8.6.13=h892fb3f_3
  - tktable=2.10=h3c7de25_7
  - tzdata=2025c=hc9c84f9_1
  - zeromq=4.3.5=h888dc83_9
  - zlib=1.3.1=h8359307_2
  - zstd=1.5.7=hbf9d68e_6
prefix: /opt/anaconda3/envs/st_env
